### ISSUE TITLE
Modules cannot parse file

### ISSUE THREAD

**Issue by Redsam121** [gurumukhi/youtube-screenshot#4] opened 2019-08-31 02:44 UTC
Almost every editing software I've used (toon boom, after effects, illustrator, photoshop), they all have the same problem. I use the screenshots to help make colour palettes if you're wondering.
![Capture12](https://user-images.githubusercontent.com/49752963/64058344-32616c80-cbdc-11e9-8526-b13a57fe7ac4.PNG)

**Comment by gurumukhi** [comment] 2019-10-01 21:05
i will try to open a file in one of these softwares and try.

**Comment by gurumukhi** [comment] 2020-07-09 08:51
I was unable to reproduce this issue. If you can find the problem, feel free to raise the PR with the fix. Closing this issue now, you can reopen if required.

**Closed by gurumukhi** 2020-07-09 08:51 UTC

**Comment by gurumukhi** [comment] 2020-07-09 09:07
Hi @Redsam121, I have fixed the filetype in https://github.com/gurumukhi/youtube-screenshot/pull/9 & published new version. I hope this would solve this issue as well, kindly check. Thanks again for reporting the issue.
