### ISSUE TITLE
Add option to copy screenshot to clipboard

### ISSUE THREAD

**Issue by thebitstick** [gurumukhi/youtube-screenshot#8] opened 2020-07-08 11:56 UTC

**Comment by gurumukhi** [comment] 2020-07-09 09:31
https://github.com/gurumukhi/youtube-screenshot/issues/6 marked as duplicate of this issue.

**Comment by gurumukhi** [comment] 2020-07-09 10:49
Tried few ways to implement, but couldn't get it working yet. if anyone wants to pick this up you can check what I have tried on in the branch - https://github.com/gurumukhi/youtube-screenshot/compare/copy-to-clipboard?expand=1.

**Comment by joggee-fr** [comment] 2022-09-19 07:20
[FutureMillennium/Screenshot-YouTube ](https://github.com/FutureMillennium/Screenshot-YouTube) has such a feature.
I may take a look later on reporting here the option.
@thebitstick, @gurumukhi, do you have any idea for the UX part? Is it OK to add the option in the add-on preferences just like the example above, with the choice "Save as image" or "Copy to clipboard"?

**Comment by joggee-fr** [comment] 2022-10-02 09:49
I have just checked the test branch from @gurumukhi. Everything seems alright looking at the code, but the Promise returned by [navigator.clipboard.write()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write) is never resolved.
Weird, until I read theses sad lines on the documentation according to Firefox support of this API:
```
From version 87: this feature is behind thedom.events.asyncClipboard.clipboardItem preferences (needs to be set to true). To change preferences in Firefox, visit about:config.
```
😥

After setting the variable to true in Firefox configuration, the copy to clipboard feature is working. But I am not comfortable with such a solution. I don't find yet an alternative to copy blob in the clipboard supported by Firefox.

**Comment by joggee-fr** [comment] 2022-10-02 21:01
Ok, I got a solution using [background script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts) and [clipboard.setImageData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData). Implemented this way, the feature will be Firefox only. README indicating the extension as cross browser will not be right anymore.
Do you want me to create such a PR?

**Comment by gurumukhi** [comment] 2022-10-03 05:22
Yes, we can mention this in README.

**Comment by joggee-fr** [comment] 2022-10-03 21:32
I have just opened PR #22 using the specific Firefox API I described above. Please take a look and let me know if OK.

**Comment by joggee-fr** [comment] 2022-12-13 22:29
Hi @gurumukhi, it seems you did not have yet time to publish a new version of the add-on in the Mozilla store. This issue may be closed when it will be available there.
By the way, I did not test it myself, but have you checked Github Action to automatically publish a new version at each tag for example?

**Comment by ashleymavericks** [comment] 2022-12-20 22:26
@joggee-fr thanks for resolving this issue, much appreciated. I was actively looking for it.

**Comment by gurumukhi** [comment] 2022-12-22 07:38
Released new version (https://addons.mozilla.org/en-US/firefox/addon/youtube-screenshot-button/). Thanks @joggee-fr.

**Closed by gurumukhi** 2022-12-22 07:38 UTC
Labels: help wanted, good first issue, p2
